### ISSUE TITLE
Unknown time frequency format

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-webui#103]
This is what we get now every time ODP is queried for data sources list:

![image](https://user-images.githubusercontent.com/206773/90724100-3d664e80-e2be-11ea-8e72-e8918bc060cf.png)

**Comment by TonioF** [comment]
Has been fixed by https://github.com/CCI-Tools/cate/commit/04d8519f7f9a95a82ad8faf2c2d8026886e6516d .
