### ISSUE TITLE
Fix issues with new Cesium version

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-webui#11]
Use of Cesium 0.66 introduced several new issues:

- [x] Fix adding a point - crash, see console
- [x] Fix adding a line - no error on console, only marker points shown, but connecting line shown, no line placemark added
- [x] Fix adding a polygon - error on console, only marker points shown, but connecting line shown, no line placemark added
- [x] Fix adding a rectangle - no error on console, nothing shown, no placemark added
- [x] Fix "countries" layer almost invisible in map

**EDIT**

- [x] Fix copy CSV, WKT, GeoJSON to clipboard, it no longer works, clipboard remains empty (see #41)

**EDIT**

- [x] After drawing a few entities, selection by clicking works, then suddenly stops working, selection marker sticks to a random entity

**Comment by forman** [comment]
Progress so far:

- insertion of points works
- selection of entities not at all (markers sticks either to an entity or view center, randomly)
- insertion of other geometries works 2, or 3x, then drawing adn insertions are hidden like if they were inserted on another layer
- increasing z-Order *does not* solve the problem

**Comment by dzelge** [comment]
Sometimes the shape draws but disappears immediately.

**Comment by forman** [comment]
Fixed by #61
