### ISSUE TITLE
Error 403 after logout

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-webui#119]
After logout I see the following error

![image](https://user-images.githubusercontent.com/206773/91737269-258ca580-ebaf-11ea-8047-3f91bc04161e.png)

I guess, there is a risk, that failed logouts produce Cate WebAPI zombies.

**Comment by dzelge** [comment]
@forman Does this still happen? Cannot reproduce it.

**Comment by forman** [comment]
Now using different API. Reopen if it comes back.
