### ISSUE TITLE
Fix issues with new BlueprintJS version

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-webui#12]
Use of Blueprint 3.x introduced several new issues.

Coding issues:

- [x] Replace `src/renderer/components/Card` usages by `@blueprintjs.core.Card`

Styling issues:

- [x] Fix data store selector being too slim in width in DATA SOURCES panel.
- [x] Fix vertical non-alignment of green "Add tag" button and subsequently added tags in OPERATIONS panel.
- [x] Fix "Display range" input field not aligned with right-side "<->" button in STYLES panel.
- [x] Fix vertical non-alignment of icon and label in "Active view" control of VIEW panel.
- [x] Fix too large cell heights in LAYERS panel items.
- [x] Fix non-alignment of checkboxes and label text in LAYERS panel items.
- [x] Fix tooltip flickering in OPERATIONS panel (Add Step button).
- [x] Fix tooltip flickering in WORKSPACE panel (Resource/step properties, clean workspace buttons).
- [x] Fix tooltip flickering in VARIABLES panel (Create a time series button).

**Comment by forman** [comment]
- [ ] Fix text field style:

![image](https://user-images.githubusercontent.com/206773/75871392-c66ef380-5e0c-11ea-8e89-276a4972f9d3.png)

**Comment by forman** [comment]
- [ ] Fix misalignment in workspace dialog boxes

![image](https://user-images.githubusercontent.com/206773/75914149-8c294480-5e54-11ea-8b09-8ce0ce1ce19d.png)

**Comment by forman** [comment]
- [ ] Fix places list

![image](https://user-images.githubusercontent.com/206773/77551853-19d7dd00-6eb3-11ea-982a-abcf6ee85010.png)

**Comment by forman** [comment]
- [ ] Fix colour bars selector popup:

![image](https://user-images.githubusercontent.com/206773/77777076-4a547e00-704f-11ea-8d0e-a42dbe41ab6d.png)

**Comment by AliceBalfanz** [comment]
- [ ] Fix `Edit Operation Step`- pop-up window

![image](https://user-images.githubusercontent.com/23457217/89624674-e3659200-d896-11ea-8fd5-f0fd04493182.png)

**Comment by forman** [comment]
![image](https://user-images.githubusercontent.com/206773/89625634-77842900-d898-11ea-9727-db64120e324b.png)

**Comment by forman** [comment]
- [ ] Icon too small

**Comment by forman** [comment]
![image](https://user-images.githubusercontent.com/206773/89665462-087af480-d8d9-11ea-940d-e96fa52c2f5b.png)

- [ ] Dataset labels don't grow into free space

**Comment by forman** [comment]
![image](https://user-images.githubusercontent.com/206773/89758926-4cdcdf00-dae9-11ea-9c43-cf66387fa4c0.png)

- [ ] Wrapping and spacing broken

**Comment by forman** [comment]
> ![image](https://user-images.githubusercontent.com/206773/89758926-4cdcdf00-dae9-11ea-9c43-cf66387fa4c0.png)
> 
> * [x]  Wrapping and spacing broken

Fixed in https://github.com/CCI-Tools/cate-webui/tree/forman-64-file_choosers-v2

**Comment by pont-us** [comment]
![alignment](https://user-images.githubusercontent.com/9010180/90018599-76466800-dcad-11ea-92ee-5b4fd624c2d3.png)

[ ] Widgets vertically misaligned in operations dialog

**Comment by pont-us** [comment]
![screenshot](https://user-images.githubusercontent.com/9010180/90397854-c734d280-e098-11ea-8c0f-0e4b1261114f.png)
 - [ ] Fix horizontal alignment in "Add file data source" dialog

**Comment by forman** [comment]
![image](https://user-images.githubusercontent.com/206773/90403109-c30cb300-e0a0-11ea-92b0-70f7ffbe0fd5.png)

- [ ] Add vert. gap between workspace list and checkbox

**Comment by AliceBalfanz** [comment]
![image_2020_08_18T08_17_05_809Z](https://user-images.githubusercontent.com/23457217/90495397-da04e100-e144-11ea-9d5b-5f76989e0c57.png)

- [ ] Fix word wrapping in 'Remove Data Source'

**Comment by AliceBalfanz** [comment]
![image](https://user-images.githubusercontent.com/23457217/90495620-1c2e2280-e145-11ea-8b93-5f9369018c7d.png)

- [ ] Fix word wrapping in 'Open Dataset from File(s)'

**Comment by pont-us** [comment]
![image_2020_08_18T14_09_35_483Z](https://user-images.githubusercontent.com/9010180/90529786-62e74100-e174-11ea-8513-3628745030d8.png)

 - [x] Checkboxes and layers misaligned in Layers panel

Happens on Chrome but not on Firefox.

**Comment by pont-us** [comment]
Closing since all sub-issues now have now been fixed.
