### ISSUE TITLE
weird layout at bottom on some screens

### ISSUE THREAD

**Issue by suvarchal** [CCI-Tools/cate-webui#23]
![image](https://user-images.githubusercontent.com/15322959/75887314-e7920d00-5e29-11ea-98f9-abd22424225f.png)

Doesn't also seem related to browser (Chrome or Firefox) I am guessing it might be screen size?

**Comment by forman** [comment]
I can now reproduce this with the deployed version on JASMIN.

**Comment by forman** [comment]
Fixed (missing files in build step)
