### ISSUE TITLE
Fix copy-to-clipboard

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-webui#41]
Because we no longer have electron support, copy-to-clipboard no longer works but is used in some places:

- [x] PLACES panel action bar
- [x] WORKSPACE panel action bar
- [x] Cesium context menu
- [x] (Internal) Error message boxes

Package [clipboard-polyfill](https://github.com/lgarron/clipboard-polyfill) may be used to achieve the old functionality.

**Comment by forman** [comment]
@AliceBalfanz, @dzelge fixed this recently. Can we close this?

**Comment by AliceBalfanz** [comment]
When I try to copy a place as a csv, wkt:
![image](https://user-images.githubusercontent.com/23457217/90512969-3aa11780-e15f-11ea-9edd-3ce6f3f707d2.png)

When copying as GeoJson the content within clipboard is 'null'

**Comment by AliceBalfanz** [comment]
WORKSPACE panel action bar - there copying the workflow in different formats works very well.
