### ISSUE TITLE
Memory Leak when running the UI in Firefox

### ISSUE THREAD

**Issue by dzelge** [CCI-Tools/cate-webui#48]
## Current Behaviour

When running the webui in Firefox you can get an out-of-memory error.

## Reproduce

- Open the webui in Firefox
- Login so tat you get the Cesium globe
- Wait

After a couple of minutes the out-of-memory-error will appear,

![tt](https://user-images.githubusercontent.com/42441761/77741167-b9f94780-7014-11ea-98d8-3a93a4e4b620.png)

**Comment by forman** [comment]
Does it happen with the globes in [Cesium Sandbox](https://sandcastle.cesium.com/) too?
May also ask the CfS team if they observe similar things.

**Comment by forman** [comment]
As Firefox is a very popular browser, I make this a blocker. 
However, in Chrome, the problem does not occur.

**Comment by forman** [comment]
Seems to be fixed by #61. @AliceBalfanz and @dzelge please verify on Linux. Reopen if problem persists.
