### ISSUE TITLE
Some mouse hover info boxes are broken

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate-webui#57]
When hovering over the icons within the details section of a dataset the last icon info box does not work properly (when looking from left to right). 

![image](https://user-images.githubusercontent.com/23457217/88785351-58e3ab00-d191-11ea-915b-b684574a0b05.png)

This issue also occurs when hovering over the icons within the Details of a variable. 
Not working are the 3rd and the last icon (when looking from left to right). 

![image](https://user-images.githubusercontent.com/23457217/88784954-e7a3f800-d190-11ea-8936-9c1fbb559e03.png)

Within the operation section, for the button `Add Step` the same issue appears:
![image](https://user-images.githubusercontent.com/23457217/88785602-b2e47080-d191-11ea-801e-19606fb317de.png)

**Comment by forman** [comment]
Also mentioned in #12 .

**Comment by AliceBalfanz** [comment]
This was fixed by PR #75
