### ISSUE TITLE
Faulty filtering of datasets 

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate-webui#60]
When filtering the datasets e.g. by ecv, the first few entries are occupied by datasets containing AEROSOL, although it was not the ecv used for filtering. After scrolling further down the results list, the expected datasets containing the filtered sst appear. 

To reconstruct: 
filter datasets for 'sst' or for 'ozone' and view list of datasets. 
![image](https://user-images.githubusercontent.com/23457217/89029952-bf063480-d32f-11ea-88d1-7aa45449a049.png)

**Comment by forman** [comment]
This bug is for sure related to the other issue, where dataset IDs appear twice.

**Comment by forman** [comment]
Verified.
