### ISSUE TITLE
Dataset ID appears twice

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-webui#70]
The dataset with ID `esacci.AEROSOL.satellite-orbit-frequency.L2P.AER_PRODUCTS.ATSR-2.ERS-2.SU.4-21.r1` appears twice in the list:

![image](https://user-images.githubusercontent.com/206773/89703746-dd7eb800-d94d-11ea-86e8-eed927bba6e4.png)

This causes severe other problems. E.g. the item cannot be selected and broken filtering, see #60.

**Comment by forman** [comment]
It is back :(

**Comment by AliceBalfanz** [comment]
again, cannot reproduce
