### ISSUE TITLE
File selector - cannot type 'slash' in the path selection

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate-webui#72]
In case one wants to write the path to a directory via the file selector, the character 'Slash' does not appear. Backslash does not work either.

![image](https://user-images.githubusercontent.com/23457217/89981227-d0c2d280-dc73-11ea-8af8-4e491770fe0f.png)

Slash works without any issues in this window though: 
![image](https://user-images.githubusercontent.com/23457217/89981450-2eefb580-dc74-11ea-8936-5bc996f4f05b.png)

**Comment by forman** [comment]
This is a blocker as it prevents file selections for file path parameters in OPERATIONS panel.

**Comment by forman** [comment]
Fixing this in https://github.com/CCI-Tools/cate-webui/tree/forman-64-file_choosers-v3
