### ISSUE TITLE
Cate UI cannot open dataset when another dataset in another store has the same ID

### ISSUE THREAD

**Issue by TonioF** [CCI-Tools/cate-webui#85]
If this happens, the following exception is thrown:
![image](https://user-images.githubusercontent.com/1598254/90497584-86e05d80-e147-11ea-894e-9ec0fe525f60.png)

**Comment by forman** [comment]
@TonioF an ID should of course be unique as they are *identifiers*. If two stores have data sources with same ID, this is a problem of the configuration of the backend, not the UI.

**Comment by TonioF** [comment]
Solved by https://github.com/CCI-Tools/cate/pull/923
