### ISSUE TITLE
Add Operation Step - file path selection not working

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate-webui#91]
When configuring a operation on a dataset, there is the possibility to select the file path (e.g. when plotting a hovmöller diagram). 
When selecting the path via the selector I can select my workspace, and then click on 'save file' however this has no effect in the 'Add Operation Step' window - the filepath is still empty, but I can click on 'Add step' anyways.

![image](https://user-images.githubusercontent.com/23457217/90618238-fcaffc00-e20f-11ea-8bd9-0661267c1864.png)
![image](https://user-images.githubusercontent.com/23457217/90618273-08032780-e210-11ea-8253-255103e5ee96.png)

**Comment by forman** [comment]
You must enter a filename.

However, the "Save File" button should be diabled while you haven't done so.

**Comment by dzelge** [comment]
Die Verzeichnisliste auf der linken Seite ist nicht sortiert.

**Comment by forman** [comment]
Stimmt.

**Comment by AliceBalfanz** [comment]
> However, the "Save File" button should be diabled while you haven't done so.

Yes, that would be helpful for the user :) I will create a new issue and closing this one. Because I did not select a file.

**Comment by AliceBalfanz** [comment]
New issue opened here: 
https://github.com/CCI-Tools/cate-webui/issues/95
