### ISSUE TITLE
Warn user when no file path is given in 'Add Operation Step'

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate-webui#95]
When configuring a operation on a dataset, there is the possibility to select the file path (e.g. when plotting a hovmöller diagram).
When selecting the path via the selector I can select my workspace directory, and then click on 'save file'  and no warning is given, that I have only selected a directory and not a file or given a file name. The user should be warned to provide a file name.

![image](https://user-images.githubusercontent.com/23457217/90629548-db570c00-e21f-11ea-98a6-52f6e52d50f5.png)
![image](https://user-images.githubusercontent.com/23457217/90629555-deea9300-e21f-11ea-9cea-897e2e53d3e5.png)

**Comment by forman** [comment]
Closing this in favor of #102
