### ISSUE TITLE
Tooltip flickering for some variable names

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate-webui#97]
Having selected a dataset and then viewing the variables in the Variables view, one can hover over the short names and the long names are displayed in the tooltip. However, for some variables this tooltip flickers which makes the long name unreadable:

![image](https://user-images.githubusercontent.com/23457217/90631235-a7c9b100-e222-11ea-88ca-998906cbe972.png)

The solution could be to wrap the content of the tooltip as done for the colormap descriptions tooltips.

**Comment by forman** [comment]
Well done.
